--------------------------------------------------------
--  Fichier créé - samedi-décembre-04-2021   
--------------------------------------------------------
DROP TABLE "AZIZ"."AVION";
DROP TABLE "AZIZ"."EMPLACEMENT";
DROP TABLE "AZIZ"."EMPLOYE";
DROP TABLE "AZIZ"."ENTRETIENT";
DROP TABLE "AZIZ"."GERER";
DROP TABLE "AZIZ"."TICKET";
--------------------------------------------------------
--  DDL for Table AVION
--------------------------------------------------------

  CREATE TABLE "AZIZ"."AVION" 
   (	"CODE" NUMBER, 
	"DEPART" VARCHAR2(20 BYTE), 
	"ARRIVEE" VARCHAR2(20 BYTE), 
	"DUREE" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"NBPLACE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLACEMENT
--------------------------------------------------------

  CREATE TABLE "AZIZ"."EMPLACEMENT" 
   (	"NUM" NUMBER, 
	"NOM_EMP" VARCHAR2(20 BYTE), 
	"DIMENSION" NUMBER, 
	"RESERVATION" VARCHAR2(20 BYTE), 
	"LIBERATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "AZIZ"."EMPLOYE" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE" VARCHAR2(20 BYTE), 
	"NUM_TEL" NUMBER, 
	"EMAIL" VARCHAR2(20 BYTE), 
	"ADRESS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENTRETIENT
--------------------------------------------------------

  CREATE TABLE "AZIZ"."ENTRETIENT" 
   (	"CODE" VARCHAR2(20 BYTE), 
	"DATE_ENTRETIENT" VARCHAR2(20 BYTE), 
	"COLUMN1" VARCHAR2(20 BYTE), 
	"COLUMN2" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GERER
--------------------------------------------------------

  CREATE TABLE "AZIZ"."GERER" 
   (	"CIN" NUMBER, 
	"CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TICKET
--------------------------------------------------------

  CREATE TABLE "AZIZ"."TICKET" 
   (	"COLUMN1" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AZIZ.AVION
SET DEFINE OFF;
Insert into AZIZ.AVION (CODE,DEPART,ARRIVEE,DUREE,PRIX,NBPLACE) values ('16','vfg','vfg','vg','vgh','5');
Insert into AZIZ.AVION (CODE,DEPART,ARRIVEE,DUREE,PRIX,NBPLACE) values ('651','yvgb','vfgh','vgh','vfgh','15');
Insert into AZIZ.AVION (CODE,DEPART,ARRIVEE,DUREE,PRIX,NBPLACE) values ('41','bhj','ghb','gbhj','hbj','32');
Insert into AZIZ.AVION (CODE,DEPART,ARRIVEE,DUREE,PRIX,NBPLACE) values ('6485','bhj','hg','vghb','hgb','25');
Insert into AZIZ.AVION (CODE,DEPART,ARRIVEE,DUREE,PRIX,NBPLACE) values ('4685','jbh','bhj','hjb','hbj','465');
Insert into AZIZ.AVION (CODE,DEPART,ARRIVEE,DUREE,PRIX,NBPLACE) values ('64','u','bhj','ubh','bhj','645');
Insert into AZIZ.AVION (CODE,DEPART,ARRIVEE,DUREE,PRIX,NBPLACE) values ('332','B','HBJ','BHJ','JBH','514');
Insert into AZIZ.AVION (CODE,DEPART,ARRIVEE,DUREE,PRIX,NBPLACE) values ('512','u??hojip','hujiopko','8451','52','852');
Insert into AZIZ.AVION (CODE,DEPART,ARRIVEE,DUREE,PRIX,NBPLACE) values ('345','bgf','nhf','ghf','752','2574');
REM INSERTING into AZIZ.EMPLACEMENT
SET DEFINE OFF;
Insert into AZIZ.EMPLACEMENT (NUM,NOM_EMP,DIMENSION,RESERVATION,LIBERATION) values ('2561','bv','562','ghbijn','jik,j');
Insert into AZIZ.EMPLACEMENT (NUM,NOM_EMP,DIMENSION,RESERVATION,LIBERATION) values ('456','645','465','64','645');
REM INSERTING into AZIZ.EMPLOYE
SET DEFINE OFF;
Insert into AZIZ.EMPLOYE (CIN,NOM,PRENOM,SEXE,DATE_NAISSANCE,NUM_TEL,EMAIL,ADRESS) values ('3465','htfrg','tgdf','Homme','01-JAN-00','3654','hg','hfgb');
REM INSERTING into AZIZ.ENTRETIENT
SET DEFINE OFF;
REM INSERTING into AZIZ.GERER
SET DEFINE OFF;
REM INSERTING into AZIZ.TICKET
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index AVION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."AVION_PK" ON "AZIZ"."AVION" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLACEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."EMPLACEMENT_PK" ON "AZIZ"."EMPLACEMENT" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."EMPLOYE_PK" ON "AZIZ"."EMPLOYE" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENTRETIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."ENTRETIENT_PK" ON "AZIZ"."ENTRETIENT" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TICKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."TICKET_PK" ON "AZIZ"."TICKET" ("COLUMN1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AVION
--------------------------------------------------------

  ALTER TABLE "AZIZ"."AVION" ADD CONSTRAINT "AVION_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."AVION" MODIFY ("NBPLACE" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."AVION" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."AVION" MODIFY ("DUREE" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."AVION" MODIFY ("ARRIVEE" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."AVION" MODIFY ("DEPART" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."AVION" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLACEMENT
--------------------------------------------------------

  ALTER TABLE "AZIZ"."EMPLACEMENT" ADD CONSTRAINT "EMPLACEMENT_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."EMPLACEMENT" MODIFY ("LIBERATION" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."EMPLACEMENT" MODIFY ("RESERVATION" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."EMPLACEMENT" MODIFY ("DIMENSION" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."EMPLACEMENT" MODIFY ("NOM_EMP" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."EMPLACEMENT" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "AZIZ"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."EMPLOYE" MODIFY ("ADRESS" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."EMPLOYE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."EMPLOYE" MODIFY ("NUM_TEL" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."EMPLOYE" MODIFY ("DATE_NAISSANCE" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."EMPLOYE" MODIFY ("SEXE" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."EMPLOYE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."EMPLOYE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."EMPLOYE" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENTRETIENT
--------------------------------------------------------

  ALTER TABLE "AZIZ"."ENTRETIENT" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "AZIZ"."ENTRETIENT" ADD CONSTRAINT "ENTRETIENT_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "AZIZ"."TICKET" ADD CONSTRAINT "TICKET_PK" PRIMARY KEY ("COLUMN1")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AZIZ"."TICKET" MODIFY ("COLUMN1" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table GERER
--------------------------------------------------------

  ALTER TABLE "AZIZ"."GERER" ADD CONSTRAINT "GERER_FK2" FOREIGN KEY ("CIN")
	  REFERENCES "AZIZ"."AVION" ("CODE") ENABLE;
  ALTER TABLE "AZIZ"."GERER" ADD CONSTRAINT "TABLE1_FK1" FOREIGN KEY ("CIN")
	  REFERENCES "AZIZ"."EMPLOYE" ("CIN") ENABLE;
