/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableView>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget_integration;
    QWidget *page;
    QLabel *label_username;
    QLabel *label_password;
    QLineEdit *lineEdit_username;
    QLineEdit *lineEdit_password;
    QPushButton *pushButton_login;
    QLabel *label_photo_Login;
    QLabel *label;
    QWidget *page_5;
    QPushButton *pushButton_gestion_employer;
    QPushButton *pushButton_gestion_avion;
    QPushButton *pushButton_emplacement;
    QLabel *label_icon_employe;
    QLabel *label_icon_avion;
    QLabel *label_icon_emplacement;
    QLabel *label_photo_pagecommande;
    QWidget *page_2;
    QTableView *table_Emplacement;
    QLineEdit *lineEdit_reservation;
    QPushButton *pushButton_Excel;
    QLineEdit *lineEdit_dimension;
    QLabel *label_num;
    QLabel *label_liberation;
    QPushButton *pushButton_supprimer_Emplacement;
    QLabel *label_nom;
    QPushButton *pushButton_afficher_Emplacement;
    QLineEdit *lineEdit_nom_emplacement;
    QLineEdit *lineEdit_liberation;
    QLabel *label_Rechercher;
    QLabel *label_dimension;
    QComboBox *comboBox_trier_Emplacement;
    QLineEdit *lineEdit_recherche_emplacement;
    QPushButton *pushButton_modifier_Emplacement;
    QLineEdit *lineEdit_num;
    QLabel *label_reservation;
    QPushButton *pushButton_ajouter_Emplacement;
    QPushButton *pushButton_retour_emplacement;
    QLabel *label_photo_Emplacement;
    QWidget *page_3;
    QTableView *table_employe;
    QLabel *label_CIN;
    QLineEdit *lineEdit_Adress;
    QPushButton *pushButton_Supprimer;
    QLabel *label_Nom;
    QLabel *label_Num_Tel;
    QLabel *label_photo_Employe;
    QLabel *label_Sexe;
    QPushButton *pushButton_PDF;
    QPushButton *pushButton_MIseAJour;
    QLineEdit *lineEdit_Nom;
    QLineEdit *lineEdit_Num_Tel;
    QLineEdit *lineEdit_CIN;
    QLineEdit *lineEdit_Email;
    QLabel *label_Date_naissance;
    QComboBox *comboBox_tri;
    QLabel *label_Prenom;
    QLineEdit *lineEdit_Prenom;
    QPushButton *pushButton_Afficher;
    QComboBox *comboBox_Sexe;
    QLineEdit *lineEdit_recherche;
    QLabel *label_Recherche_Employe;
    QLabel *label_Email;
    QLabel *label_Adress;
    QDateEdit *dateEdit_naissance;
    QPushButton *pushButton_Ajouter;
    QPushButton *pushButton_Reset;
    QPushButton *pushButton_retour_employer;
    QWidget *page_4;
    QTableView *table_avion;
    QPushButton *pushButton_miseajouravion;
    QLineEdit *lineEdit_departavion;
    QPushButton *pushButton_PDFavion;
    QLineEdit *lineEdit_nbplaceavion;
    QPushButton *pushButton_ajouteravion;
    QPushButton *pushButton_imprimeravion;
    QLineEdit *lineEdit_prixavion;
    QLineEdit *lineEdit_Rechercheavion;
    QLabel *label_arrivee;
    QLabel *label_nbplace;
    QLabel *label_duree;
    QPushButton *pushButton_afficheravion;
    QLabel *label_code;
    QLabel *label_Recherche_avion;
    QLineEdit *lineEdit_arriveeavion;
    QPushButton *pushButton_supprimeravion;
    QLabel *label_photo_avion;
    QPushButton *pushButton_statestiqueavion;
    QLineEdit *lineEdit_dureevolavion;
    QLabel *label_prix;
    QLabel *label_depart;
    QComboBox *comboBox_trier_avion;
    QLineEdit *lineEdit_codeavion;
    QPushButton *pushButton_retour_avion;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(731, 580);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        stackedWidget_integration = new QStackedWidget(centralwidget);
        stackedWidget_integration->setObjectName(QStringLiteral("stackedWidget_integration"));
        stackedWidget_integration->setGeometry(QRect(0, 10, 721, 1021));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        label_username = new QLabel(page);
        label_username->setObjectName(QStringLiteral("label_username"));
        label_username->setGeometry(QRect(180, 190, 160, 30));
        QFont font;
        font.setFamily(QStringLiteral("Times New Roman"));
        font.setPointSize(20);
        font.setBold(true);
        font.setWeight(75);
        label_username->setFont(font);
        label_password = new QLabel(page);
        label_password->setObjectName(QStringLiteral("label_password"));
        label_password->setGeometry(QRect(180, 250, 150, 30));
        label_password->setFont(font);
        lineEdit_username = new QLineEdit(page);
        lineEdit_username->setObjectName(QStringLiteral("lineEdit_username"));
        lineEdit_username->setGeometry(QRect(340, 188, 170, 40));
        QFont font1;
        font1.setPointSize(15);
        lineEdit_username->setFont(font1);
        lineEdit_password = new QLineEdit(page);
        lineEdit_password->setObjectName(QStringLiteral("lineEdit_password"));
        lineEdit_password->setGeometry(QRect(340, 246, 170, 40));
        lineEdit_password->setFont(font1);
        lineEdit_password->setEchoMode(QLineEdit::Password);
        pushButton_login = new QPushButton(page);
        pushButton_login->setObjectName(QStringLiteral("pushButton_login"));
        pushButton_login->setGeometry(QRect(280, 340, 140, 50));
        QFont font2;
        font2.setFamily(QStringLiteral("Times New Roman"));
        font2.setPointSize(15);
        font2.setItalic(true);
        pushButton_login->setFont(font2);
        pushButton_login->setCursor(QCursor(Qt::PointingHandCursor));
        label_photo_Login = new QLabel(page);
        label_photo_Login->setObjectName(QStringLiteral("label_photo_Login"));
        label_photo_Login->setGeometry(QRect(6, -67, 711, 651));
        label_photo_Login->setPixmap(QPixmap(QString::fromUtf8("photo_Login_Qt.jpg")));
        label = new QLabel(page);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(222, 120, 251, 40));
        QFont font3;
        font3.setFamily(QStringLiteral("Times New Roman"));
        font3.setPointSize(20);
        font3.setBold(false);
        font3.setUnderline(false);
        font3.setWeight(50);
        label->setFont(font3);
        label->setTextFormat(Qt::AutoText);
        stackedWidget_integration->addWidget(page);
        label_photo_Login->raise();
        label_username->raise();
        label_password->raise();
        lineEdit_username->raise();
        lineEdit_password->raise();
        pushButton_login->raise();
        label->raise();
        page_5 = new QWidget();
        page_5->setObjectName(QStringLiteral("page_5"));
        pushButton_gestion_employer = new QPushButton(page_5);
        pushButton_gestion_employer->setObjectName(QStringLiteral("pushButton_gestion_employer"));
        pushButton_gestion_employer->setGeometry(QRect(60, 290, 180, 60));
        QFont font4;
        font4.setFamily(QStringLiteral("Times New Roman"));
        font4.setPointSize(10);
        font4.setBold(true);
        font4.setWeight(75);
        pushButton_gestion_employer->setFont(font4);
        pushButton_gestion_employer->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_gestion_employer->setMouseTracking(true);
        pushButton_gestion_avion = new QPushButton(page_5);
        pushButton_gestion_avion->setObjectName(QStringLiteral("pushButton_gestion_avion"));
        pushButton_gestion_avion->setGeometry(QRect(270, 290, 180, 60));
        pushButton_gestion_avion->setFont(font4);
        pushButton_gestion_avion->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_emplacement = new QPushButton(page_5);
        pushButton_emplacement->setObjectName(QStringLiteral("pushButton_emplacement"));
        pushButton_emplacement->setGeometry(QRect(480, 290, 180, 60));
        pushButton_emplacement->setFont(font4);
        pushButton_emplacement->setCursor(QCursor(Qt::PointingHandCursor));
        label_icon_employe = new QLabel(page_5);
        label_icon_employe->setObjectName(QStringLiteral("label_icon_employe"));
        label_icon_employe->setGeometry(QRect(80, 150, 141, 131));
        label_icon_employe->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix1/image/icon_employes.jpg")));
        label_icon_employe->setScaledContents(true);
        label_icon_avion = new QLabel(page_5);
        label_icon_avion->setObjectName(QStringLiteral("label_icon_avion"));
        label_icon_avion->setGeometry(QRect(290, 150, 150, 130));
        label_icon_avion->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix1/image/icon_avion.jpg")));
        label_icon_avion->setScaledContents(true);
        label_icon_emplacement = new QLabel(page_5);
        label_icon_emplacement->setObjectName(QStringLiteral("label_icon_emplacement"));
        label_icon_emplacement->setGeometry(QRect(490, 150, 150, 130));
        label_icon_emplacement->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix1/image/icon_emplacement.png")));
        label_icon_emplacement->setScaledContents(true);
        label_photo_pagecommande = new QLabel(page_5);
        label_photo_pagecommande->setObjectName(QStringLiteral("label_photo_pagecommande"));
        label_photo_pagecommande->setGeometry(QRect(6, -7, 711, 531));
        label_photo_pagecommande->setMouseTracking(false);
        label_photo_pagecommande->setFocusPolicy(Qt::ClickFocus);
        label_photo_pagecommande->setPixmap(QPixmap(QString::fromUtf8("photo_Login_Qt.jpg")));
        stackedWidget_integration->addWidget(page_5);
        label_photo_pagecommande->raise();
        pushButton_gestion_employer->raise();
        pushButton_gestion_avion->raise();
        pushButton_emplacement->raise();
        label_icon_employe->raise();
        label_icon_avion->raise();
        label_icon_emplacement->raise();
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        table_Emplacement = new QTableView(page_2);
        table_Emplacement->setObjectName(QStringLiteral("table_Emplacement"));
        table_Emplacement->setGeometry(QRect(60, 280, 610, 192));
        table_Emplacement->viewport()->setProperty("cursor", QVariant(QCursor(Qt::PointingHandCursor)));
        lineEdit_reservation = new QLineEdit(page_2);
        lineEdit_reservation->setObjectName(QStringLiteral("lineEdit_reservation"));
        lineEdit_reservation->setGeometry(QRect(370, 70, 120, 20));
        pushButton_Excel = new QPushButton(page_2);
        pushButton_Excel->setObjectName(QStringLiteral("pushButton_Excel"));
        pushButton_Excel->setGeometry(QRect(470, 240, 160, 30));
        pushButton_Excel->setCursor(QCursor(Qt::PointingHandCursor));
        lineEdit_dimension = new QLineEdit(page_2);
        lineEdit_dimension->setObjectName(QStringLiteral("lineEdit_dimension"));
        lineEdit_dimension->setGeometry(QRect(140, 170, 120, 20));
        label_num = new QLabel(page_2);
        label_num->setObjectName(QStringLiteral("label_num"));
        label_num->setGeometry(QRect(70, 70, 47, 14));
        QFont font5;
        font5.setPointSize(8);
        font5.setBold(false);
        font5.setWeight(50);
        label_num->setFont(font5);
        label_liberation = new QLabel(page_2);
        label_liberation->setObjectName(QStringLiteral("label_liberation"));
        label_liberation->setGeometry(QRect(300, 120, 50, 14));
        pushButton_supprimer_Emplacement = new QPushButton(page_2);
        pushButton_supprimer_Emplacement->setObjectName(QStringLiteral("pushButton_supprimer_Emplacement"));
        pushButton_supprimer_Emplacement->setGeometry(QRect(550, 130, 120, 30));
        pushButton_supprimer_Emplacement->setCursor(QCursor(Qt::PointingHandCursor));
        label_nom = new QLabel(page_2);
        label_nom->setObjectName(QStringLiteral("label_nom"));
        label_nom->setGeometry(QRect(70, 120, 47, 14));
        pushButton_afficher_Emplacement = new QPushButton(page_2);
        pushButton_afficher_Emplacement->setObjectName(QStringLiteral("pushButton_afficher_Emplacement"));
        pushButton_afficher_Emplacement->setGeometry(QRect(550, 90, 120, 30));
        pushButton_afficher_Emplacement->setCursor(QCursor(Qt::PointingHandCursor));
        lineEdit_nom_emplacement = new QLineEdit(page_2);
        lineEdit_nom_emplacement->setObjectName(QStringLiteral("lineEdit_nom_emplacement"));
        lineEdit_nom_emplacement->setGeometry(QRect(140, 120, 120, 20));
        lineEdit_liberation = new QLineEdit(page_2);
        lineEdit_liberation->setObjectName(QStringLiteral("lineEdit_liberation"));
        lineEdit_liberation->setGeometry(QRect(370, 120, 120, 20));
        label_Rechercher = new QLabel(page_2);
        label_Rechercher->setObjectName(QStringLiteral("label_Rechercher"));
        label_Rechercher->setGeometry(QRect(280, 210, 70, 14));
        label_dimension = new QLabel(page_2);
        label_dimension->setObjectName(QStringLiteral("label_dimension"));
        label_dimension->setGeometry(QRect(70, 170, 70, 14));
        comboBox_trier_Emplacement = new QComboBox(page_2);
        comboBox_trier_Emplacement->setObjectName(QStringLiteral("comboBox_trier_Emplacement"));
        comboBox_trier_Emplacement->setGeometry(QRect(100, 240, 150, 28));
        comboBox_trier_Emplacement->setCursor(QCursor(Qt::PointingHandCursor));
        lineEdit_recherche_emplacement = new QLineEdit(page_2);
        lineEdit_recherche_emplacement->setObjectName(QStringLiteral("lineEdit_recherche_emplacement"));
        lineEdit_recherche_emplacement->setGeometry(QRect(280, 240, 160, 28));
        pushButton_modifier_Emplacement = new QPushButton(page_2);
        pushButton_modifier_Emplacement->setObjectName(QStringLiteral("pushButton_modifier_Emplacement"));
        pushButton_modifier_Emplacement->setGeometry(QRect(550, 170, 120, 30));
        pushButton_modifier_Emplacement->setCursor(QCursor(Qt::PointingHandCursor));
        lineEdit_num = new QLineEdit(page_2);
        lineEdit_num->setObjectName(QStringLiteral("lineEdit_num"));
        lineEdit_num->setGeometry(QRect(140, 70, 120, 20));
        label_reservation = new QLabel(page_2);
        label_reservation->setObjectName(QStringLiteral("label_reservation"));
        label_reservation->setGeometry(QRect(300, 70, 60, 14));
        pushButton_ajouter_Emplacement = new QPushButton(page_2);
        pushButton_ajouter_Emplacement->setObjectName(QStringLiteral("pushButton_ajouter_Emplacement"));
        pushButton_ajouter_Emplacement->setGeometry(QRect(550, 50, 120, 30));
        pushButton_ajouter_Emplacement->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_retour_emplacement = new QPushButton(page_2);
        pushButton_retour_emplacement->setObjectName(QStringLiteral("pushButton_retour_emplacement"));
        pushButton_retour_emplacement->setGeometry(QRect(570, 480, 100, 30));
        pushButton_retour_emplacement->setCursor(QCursor(Qt::PointingHandCursor));
        label_photo_Emplacement = new QLabel(page_2);
        label_photo_Emplacement->setObjectName(QStringLiteral("label_photo_Emplacement"));
        label_photo_Emplacement->setGeometry(QRect(10, -1, 711, 551));
        label_photo_Emplacement->setPixmap(QPixmap(QString::fromUtf8("photo_Login_Qt.jpg")));
        stackedWidget_integration->addWidget(page_2);
        label_photo_Emplacement->raise();
        table_Emplacement->raise();
        lineEdit_reservation->raise();
        pushButton_Excel->raise();
        lineEdit_dimension->raise();
        label_num->raise();
        label_liberation->raise();
        pushButton_supprimer_Emplacement->raise();
        label_nom->raise();
        pushButton_afficher_Emplacement->raise();
        lineEdit_nom_emplacement->raise();
        lineEdit_liberation->raise();
        label_Rechercher->raise();
        label_dimension->raise();
        comboBox_trier_Emplacement->raise();
        lineEdit_recherche_emplacement->raise();
        pushButton_modifier_Emplacement->raise();
        lineEdit_num->raise();
        label_reservation->raise();
        pushButton_ajouter_Emplacement->raise();
        pushButton_retour_emplacement->raise();
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        table_employe = new QTableView(page_3);
        table_employe->setObjectName(QStringLiteral("table_employe"));
        table_employe->setGeometry(QRect(40, 270, 610, 192));
        table_employe->viewport()->setProperty("cursor", QVariant(QCursor(Qt::PointingHandCursor)));
        label_CIN = new QLabel(page_3);
        label_CIN->setObjectName(QStringLiteral("label_CIN"));
        label_CIN->setGeometry(QRect(50, 30, 60, 16));
        lineEdit_Adress = new QLineEdit(page_3);
        lineEdit_Adress->setObjectName(QStringLiteral("lineEdit_Adress"));
        lineEdit_Adress->setGeometry(QRect(340, 150, 110, 20));
        pushButton_Supprimer = new QPushButton(page_3);
        pushButton_Supprimer->setObjectName(QStringLiteral("pushButton_Supprimer"));
        pushButton_Supprimer->setGeometry(QRect(520, 146, 130, 31));
        pushButton_Supprimer->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_Supprimer->setMouseTracking(true);
        label_Nom = new QLabel(page_3);
        label_Nom->setObjectName(QStringLiteral("label_Nom"));
        label_Nom->setGeometry(QRect(50, 70, 60, 16));
        label_Num_Tel = new QLabel(page_3);
        label_Num_Tel->setObjectName(QStringLiteral("label_Num_Tel"));
        label_Num_Tel->setGeometry(QRect(230, 70, 80, 16));
        label_photo_Employe = new QLabel(page_3);
        label_photo_Employe->setObjectName(QStringLiteral("label_photo_Employe"));
        label_photo_Employe->setGeometry(QRect(10, 0, 710, 521));
        label_photo_Employe->setCursor(QCursor(Qt::ArrowCursor));
        label_photo_Employe->setPixmap(QPixmap(QString::fromUtf8("photo_Login_Qt.jpg")));
        label_Sexe = new QLabel(page_3);
        label_Sexe->setObjectName(QStringLiteral("label_Sexe"));
        label_Sexe->setGeometry(QRect(50, 150, 80, 16));
        pushButton_PDF = new QPushButton(page_3);
        pushButton_PDF->setObjectName(QStringLiteral("pushButton_PDF"));
        pushButton_PDF->setGeometry(QRect(520, 230, 130, 31));
        pushButton_PDF->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_MIseAJour = new QPushButton(page_3);
        pushButton_MIseAJour->setObjectName(QStringLiteral("pushButton_MIseAJour"));
        pushButton_MIseAJour->setGeometry(QRect(520, 66, 130, 31));
        pushButton_MIseAJour->setCursor(QCursor(Qt::PointingHandCursor));
        lineEdit_Nom = new QLineEdit(page_3);
        lineEdit_Nom->setObjectName(QStringLiteral("lineEdit_Nom"));
        lineEdit_Nom->setGeometry(QRect(100, 70, 110, 20));
        lineEdit_Num_Tel = new QLineEdit(page_3);
        lineEdit_Num_Tel->setObjectName(QStringLiteral("lineEdit_Num_Tel"));
        lineEdit_Num_Tel->setGeometry(QRect(340, 70, 110, 20));
        lineEdit_CIN = new QLineEdit(page_3);
        lineEdit_CIN->setObjectName(QStringLiteral("lineEdit_CIN"));
        lineEdit_CIN->setGeometry(QRect(100, 30, 110, 20));
        lineEdit_Email = new QLineEdit(page_3);
        lineEdit_Email->setObjectName(QStringLiteral("lineEdit_Email"));
        lineEdit_Email->setGeometry(QRect(340, 110, 110, 20));
        label_Date_naissance = new QLabel(page_3);
        label_Date_naissance->setObjectName(QStringLiteral("label_Date_naissance"));
        label_Date_naissance->setGeometry(QRect(230, 30, 100, 16));
        comboBox_tri = new QComboBox(page_3);
        comboBox_tri->setObjectName(QStringLiteral("comboBox_tri"));
        comboBox_tri->setGeometry(QRect(360, 230, 140, 31));
        label_Prenom = new QLabel(page_3);
        label_Prenom->setObjectName(QStringLiteral("label_Prenom"));
        label_Prenom->setGeometry(QRect(50, 110, 60, 16));
        lineEdit_Prenom = new QLineEdit(page_3);
        lineEdit_Prenom->setObjectName(QStringLiteral("lineEdit_Prenom"));
        lineEdit_Prenom->setGeometry(QRect(100, 110, 110, 20));
        pushButton_Afficher = new QPushButton(page_3);
        pushButton_Afficher->setObjectName(QStringLiteral("pushButton_Afficher"));
        pushButton_Afficher->setGeometry(QRect(520, 106, 130, 31));
        pushButton_Afficher->setCursor(QCursor(Qt::PointingHandCursor));
        comboBox_Sexe = new QComboBox(page_3);
        comboBox_Sexe->setObjectName(QStringLiteral("comboBox_Sexe"));
        comboBox_Sexe->setGeometry(QRect(100, 150, 110, 21));
        lineEdit_recherche = new QLineEdit(page_3);
        lineEdit_recherche->setObjectName(QStringLiteral("lineEdit_recherche"));
        lineEdit_recherche->setGeometry(QRect(200, 230, 140, 31));
        label_Recherche_Employe = new QLabel(page_3);
        label_Recherche_Employe->setObjectName(QStringLiteral("label_Recherche_Employe"));
        label_Recherche_Employe->setGeometry(QRect(200, 210, 80, 16));
        label_Email = new QLabel(page_3);
        label_Email->setObjectName(QStringLiteral("label_Email"));
        label_Email->setGeometry(QRect(230, 110, 80, 16));
        label_Adress = new QLabel(page_3);
        label_Adress->setObjectName(QStringLiteral("label_Adress"));
        label_Adress->setGeometry(QRect(230, 150, 80, 16));
        dateEdit_naissance = new QDateEdit(page_3);
        dateEdit_naissance->setObjectName(QStringLiteral("dateEdit_naissance"));
        dateEdit_naissance->setGeometry(QRect(340, 30, 110, 22));
        pushButton_Ajouter = new QPushButton(page_3);
        pushButton_Ajouter->setObjectName(QStringLiteral("pushButton_Ajouter"));
        pushButton_Ajouter->setGeometry(QRect(520, 26, 130, 31));
        pushButton_Ajouter->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_Reset = new QPushButton(page_3);
        pushButton_Reset->setObjectName(QStringLiteral("pushButton_Reset"));
        pushButton_Reset->setGeometry(QRect(40, 230, 140, 31));
        pushButton_Reset->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_retour_employer = new QPushButton(page_3);
        pushButton_retour_employer->setObjectName(QStringLiteral("pushButton_retour_employer"));
        pushButton_retour_employer->setGeometry(QRect(540, 470, 100, 30));
        pushButton_retour_employer->setCursor(QCursor(Qt::PointingHandCursor));
        stackedWidget_integration->addWidget(page_3);
        label_photo_Employe->raise();
        table_employe->raise();
        label_CIN->raise();
        lineEdit_Adress->raise();
        pushButton_Supprimer->raise();
        label_Nom->raise();
        label_Num_Tel->raise();
        label_Sexe->raise();
        pushButton_PDF->raise();
        pushButton_MIseAJour->raise();
        lineEdit_Nom->raise();
        lineEdit_Num_Tel->raise();
        lineEdit_CIN->raise();
        lineEdit_Email->raise();
        label_Date_naissance->raise();
        comboBox_tri->raise();
        label_Prenom->raise();
        lineEdit_Prenom->raise();
        pushButton_Afficher->raise();
        comboBox_Sexe->raise();
        lineEdit_recherche->raise();
        label_Recherche_Employe->raise();
        label_Email->raise();
        label_Adress->raise();
        dateEdit_naissance->raise();
        pushButton_Ajouter->raise();
        pushButton_Reset->raise();
        pushButton_retour_employer->raise();
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        table_avion = new QTableView(page_4);
        table_avion->setObjectName(QStringLiteral("table_avion"));
        table_avion->setGeometry(QRect(40, 260, 631, 211));
        table_avion->viewport()->setProperty("cursor", QVariant(QCursor(Qt::PointingHandCursor)));
        pushButton_miseajouravion = new QPushButton(page_4);
        pushButton_miseajouravion->setObjectName(QStringLiteral("pushButton_miseajouravion"));
        pushButton_miseajouravion->setGeometry(QRect(520, 150, 120, 30));
        pushButton_miseajouravion->setCursor(QCursor(Qt::PointingHandCursor));
        lineEdit_departavion = new QLineEdit(page_4);
        lineEdit_departavion->setObjectName(QStringLiteral("lineEdit_departavion"));
        lineEdit_departavion->setGeometry(QRect(130, 98, 113, 20));
        pushButton_PDFavion = new QPushButton(page_4);
        pushButton_PDFavion->setObjectName(QStringLiteral("pushButton_PDFavion"));
        pushButton_PDFavion->setGeometry(QRect(430, 220, 110, 30));
        pushButton_PDFavion->setCursor(QCursor(Qt::PointingHandCursor));
        lineEdit_nbplaceavion = new QLineEdit(page_4);
        lineEdit_nbplaceavion->setObjectName(QStringLiteral("lineEdit_nbplaceavion"));
        lineEdit_nbplaceavion->setGeometry(QRect(360, 138, 113, 20));
        pushButton_ajouteravion = new QPushButton(page_4);
        pushButton_ajouteravion->setObjectName(QStringLiteral("pushButton_ajouteravion"));
        pushButton_ajouteravion->setGeometry(QRect(520, 30, 120, 30));
        pushButton_ajouteravion->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_imprimeravion = new QPushButton(page_4);
        pushButton_imprimeravion->setObjectName(QStringLiteral("pushButton_imprimeravion"));
        pushButton_imprimeravion->setGeometry(QRect(300, 220, 110, 30));
        pushButton_imprimeravion->setCursor(QCursor(Qt::PointingHandCursor));
        lineEdit_prixavion = new QLineEdit(page_4);
        lineEdit_prixavion->setObjectName(QStringLiteral("lineEdit_prixavion"));
        lineEdit_prixavion->setGeometry(QRect(360, 98, 113, 20));
        lineEdit_Rechercheavion = new QLineEdit(page_4);
        lineEdit_Rechercheavion->setObjectName(QStringLiteral("lineEdit_Rechercheavion"));
        lineEdit_Rechercheavion->setGeometry(QRect(170, 220, 110, 30));
        label_arrivee = new QLabel(page_4);
        label_arrivee->setObjectName(QStringLiteral("label_arrivee"));
        label_arrivee->setGeometry(QRect(60, 140, 47, 14));
        label_nbplace = new QLabel(page_4);
        label_nbplace->setObjectName(QStringLiteral("label_nbplace"));
        label_nbplace->setGeometry(QRect(300, 140, 47, 14));
        label_duree = new QLabel(page_4);
        label_duree->setObjectName(QStringLiteral("label_duree"));
        label_duree->setGeometry(QRect(300, 60, 47, 14));
        pushButton_afficheravion = new QPushButton(page_4);
        pushButton_afficheravion->setObjectName(QStringLiteral("pushButton_afficheravion"));
        pushButton_afficheravion->setGeometry(QRect(520, 70, 120, 30));
        pushButton_afficheravion->setCursor(QCursor(Qt::PointingHandCursor));
        label_code = new QLabel(page_4);
        label_code->setObjectName(QStringLiteral("label_code"));
        label_code->setGeometry(QRect(60, 60, 47, 14));
        label_Recherche_avion = new QLabel(page_4);
        label_Recherche_avion->setObjectName(QStringLiteral("label_Recherche_avion"));
        label_Recherche_avion->setGeometry(QRect(170, 200, 51, 16));
        QFont font6;
        font6.setFamily(QStringLiteral("Times New Roman"));
        font6.setPointSize(8);
        font6.setBold(false);
        font6.setItalic(false);
        font6.setWeight(50);
        label_Recherche_avion->setFont(font6);
        lineEdit_arriveeavion = new QLineEdit(page_4);
        lineEdit_arriveeavion->setObjectName(QStringLiteral("lineEdit_arriveeavion"));
        lineEdit_arriveeavion->setGeometry(QRect(130, 139, 113, 20));
        pushButton_supprimeravion = new QPushButton(page_4);
        pushButton_supprimeravion->setObjectName(QStringLiteral("pushButton_supprimeravion"));
        pushButton_supprimeravion->setGeometry(QRect(520, 110, 120, 30));
        pushButton_supprimeravion->setCursor(QCursor(Qt::PointingHandCursor));
        label_photo_avion = new QLabel(page_4);
        label_photo_avion->setObjectName(QStringLiteral("label_photo_avion"));
        label_photo_avion->setGeometry(QRect(10, -20, 711, 581));
        label_photo_avion->setPixmap(QPixmap(QString::fromUtf8("photo_Login_Qt.jpg")));
        pushButton_statestiqueavion = new QPushButton(page_4);
        pushButton_statestiqueavion->setObjectName(QStringLiteral("pushButton_statestiqueavion"));
        pushButton_statestiqueavion->setGeometry(QRect(560, 220, 110, 30));
        pushButton_statestiqueavion->setCursor(QCursor(Qt::PointingHandCursor));
        lineEdit_dureevolavion = new QLineEdit(page_4);
        lineEdit_dureevolavion->setObjectName(QStringLiteral("lineEdit_dureevolavion"));
        lineEdit_dureevolavion->setGeometry(QRect(360, 59, 113, 20));
        label_prix = new QLabel(page_4);
        label_prix->setObjectName(QStringLiteral("label_prix"));
        label_prix->setGeometry(QRect(300, 100, 47, 14));
        label_depart = new QLabel(page_4);
        label_depart->setObjectName(QStringLiteral("label_depart"));
        label_depart->setGeometry(QRect(60, 100, 50, 14));
        comboBox_trier_avion = new QComboBox(page_4);
        comboBox_trier_avion->setObjectName(QStringLiteral("comboBox_trier_avion"));
        comboBox_trier_avion->setGeometry(QRect(40, 220, 110, 30));
        comboBox_trier_avion->setCursor(QCursor(Qt::PointingHandCursor));
        lineEdit_codeavion = new QLineEdit(page_4);
        lineEdit_codeavion->setObjectName(QStringLiteral("lineEdit_codeavion"));
        lineEdit_codeavion->setGeometry(QRect(130, 58, 113, 20));
        lineEdit_codeavion->setEchoMode(QLineEdit::Normal);
        pushButton_retour_avion = new QPushButton(page_4);
        pushButton_retour_avion->setObjectName(QStringLiteral("pushButton_retour_avion"));
        pushButton_retour_avion->setGeometry(QRect(560, 480, 100, 30));
        pushButton_retour_avion->setCursor(QCursor(Qt::PointingHandCursor));
        stackedWidget_integration->addWidget(page_4);
        label_photo_avion->raise();
        table_avion->raise();
        pushButton_miseajouravion->raise();
        lineEdit_departavion->raise();
        pushButton_PDFavion->raise();
        lineEdit_nbplaceavion->raise();
        pushButton_ajouteravion->raise();
        pushButton_imprimeravion->raise();
        lineEdit_prixavion->raise();
        lineEdit_Rechercheavion->raise();
        label_arrivee->raise();
        label_nbplace->raise();
        label_duree->raise();
        pushButton_afficheravion->raise();
        label_code->raise();
        label_Recherche_avion->raise();
        lineEdit_arriveeavion->raise();
        pushButton_supprimeravion->raise();
        pushButton_statestiqueavion->raise();
        lineEdit_dureevolavion->raise();
        label_prix->raise();
        label_depart->raise();
        comboBox_trier_avion->raise();
        lineEdit_codeavion->raise();
        pushButton_retour_avion->raise();
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 731, 22));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        MainWindow->setStatusBar(statusbar);
        QWidget::setTabOrder(lineEdit_username, lineEdit_password);
        QWidget::setTabOrder(lineEdit_password, pushButton_login);
        QWidget::setTabOrder(pushButton_login, pushButton_gestion_employer);
        QWidget::setTabOrder(pushButton_gestion_employer, pushButton_gestion_avion);
        QWidget::setTabOrder(pushButton_gestion_avion, pushButton_emplacement);
        QWidget::setTabOrder(pushButton_emplacement, lineEdit_num);
        QWidget::setTabOrder(lineEdit_num, lineEdit_nom_emplacement);
        QWidget::setTabOrder(lineEdit_nom_emplacement, lineEdit_dimension);
        QWidget::setTabOrder(lineEdit_dimension, lineEdit_reservation);
        QWidget::setTabOrder(lineEdit_reservation, lineEdit_liberation);
        QWidget::setTabOrder(lineEdit_liberation, pushButton_ajouter_Emplacement);
        QWidget::setTabOrder(pushButton_ajouter_Emplacement, pushButton_afficher_Emplacement);
        QWidget::setTabOrder(pushButton_afficher_Emplacement, pushButton_supprimer_Emplacement);
        QWidget::setTabOrder(pushButton_supprimer_Emplacement, pushButton_modifier_Emplacement);
        QWidget::setTabOrder(pushButton_modifier_Emplacement, comboBox_trier_Emplacement);
        QWidget::setTabOrder(comboBox_trier_Emplacement, lineEdit_recherche_emplacement);
        QWidget::setTabOrder(lineEdit_recherche_emplacement, pushButton_Excel);
        QWidget::setTabOrder(pushButton_Excel, table_Emplacement);
        QWidget::setTabOrder(table_Emplacement, lineEdit_CIN);
        QWidget::setTabOrder(lineEdit_CIN, lineEdit_Nom);
        QWidget::setTabOrder(lineEdit_Nom, lineEdit_Prenom);
        QWidget::setTabOrder(lineEdit_Prenom, comboBox_Sexe);
        QWidget::setTabOrder(comboBox_Sexe, dateEdit_naissance);
        QWidget::setTabOrder(dateEdit_naissance, lineEdit_Num_Tel);
        QWidget::setTabOrder(lineEdit_Num_Tel, lineEdit_Email);
        QWidget::setTabOrder(lineEdit_Email, lineEdit_Adress);
        QWidget::setTabOrder(lineEdit_Adress, pushButton_Ajouter);
        QWidget::setTabOrder(pushButton_Ajouter, pushButton_MIseAJour);
        QWidget::setTabOrder(pushButton_MIseAJour, pushButton_Afficher);
        QWidget::setTabOrder(pushButton_Afficher, pushButton_Supprimer);
        QWidget::setTabOrder(pushButton_Supprimer, pushButton_Reset);
        QWidget::setTabOrder(pushButton_Reset, lineEdit_recherche);
        QWidget::setTabOrder(lineEdit_recherche, comboBox_tri);
        QWidget::setTabOrder(comboBox_tri, pushButton_PDF);
        QWidget::setTabOrder(pushButton_PDF, table_employe);
        QWidget::setTabOrder(table_employe, lineEdit_codeavion);
        QWidget::setTabOrder(lineEdit_codeavion, lineEdit_departavion);
        QWidget::setTabOrder(lineEdit_departavion, lineEdit_arriveeavion);
        QWidget::setTabOrder(lineEdit_arriveeavion, lineEdit_dureevolavion);
        QWidget::setTabOrder(lineEdit_dureevolavion, lineEdit_prixavion);
        QWidget::setTabOrder(lineEdit_prixavion, lineEdit_nbplaceavion);
        QWidget::setTabOrder(lineEdit_nbplaceavion, pushButton_ajouteravion);
        QWidget::setTabOrder(pushButton_ajouteravion, pushButton_afficheravion);
        QWidget::setTabOrder(pushButton_afficheravion, pushButton_supprimeravion);
        QWidget::setTabOrder(pushButton_supprimeravion, pushButton_miseajouravion);
        QWidget::setTabOrder(pushButton_miseajouravion, comboBox_trier_avion);
        QWidget::setTabOrder(comboBox_trier_avion, lineEdit_Rechercheavion);
        QWidget::setTabOrder(lineEdit_Rechercheavion, pushButton_imprimeravion);
        QWidget::setTabOrder(pushButton_imprimeravion, pushButton_PDFavion);
        QWidget::setTabOrder(pushButton_PDFavion, pushButton_statestiqueavion);
        QWidget::setTabOrder(pushButton_statestiqueavion, table_avion);
        QWidget::setTabOrder(table_avion, pushButton_retour_employer);
        QWidget::setTabOrder(pushButton_retour_employer, pushButton_retour_emplacement);
        QWidget::setTabOrder(pushButton_retour_emplacement, pushButton_retour_avion);

        retranslateUi(MainWindow);

        stackedWidget_integration->setCurrentIndex(4);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        label_username->setText(QApplication::translate("MainWindow", "Username", Q_NULLPTR));
        label_password->setText(QApplication::translate("MainWindow", "Password", Q_NULLPTR));
        pushButton_login->setText(QApplication::translate("MainWindow", "Login", Q_NULLPTR));
        label_photo_Login->setText(QString());
        label->setText(QApplication::translate("MainWindow", "SMART AEROPORT", Q_NULLPTR));
        pushButton_gestion_employer->setText(QApplication::translate("MainWindow", "Gestion des Employes", Q_NULLPTR));
        pushButton_gestion_avion->setText(QApplication::translate("MainWindow", "Gestion des Avions", Q_NULLPTR));
        pushButton_emplacement->setText(QApplication::translate("MainWindow", "Gestion des Emplacements", Q_NULLPTR));
        label_icon_employe->setText(QString());
        label_icon_avion->setText(QString());
        label_icon_emplacement->setText(QString());
        label_photo_pagecommande->setText(QString());
        pushButton_Excel->setText(QApplication::translate("MainWindow", "generer un fichier excell", Q_NULLPTR));
        label_num->setText(QApplication::translate("MainWindow", "Num", Q_NULLPTR));
        label_liberation->setText(QApplication::translate("MainWindow", "Liberation", Q_NULLPTR));
        pushButton_supprimer_Emplacement->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        label_nom->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        pushButton_afficher_Emplacement->setText(QApplication::translate("MainWindow", "Afficher", Q_NULLPTR));
        label_Rechercher->setText(QApplication::translate("MainWindow", "Recherche :", Q_NULLPTR));
        label_dimension->setText(QApplication::translate("MainWindow", "Dimension", Q_NULLPTR));
        comboBox_trier_Emplacement->clear();
        comboBox_trier_Emplacement->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "    Trier", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Tri par Num", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Tri par Nom", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Tri par Dimension", Q_NULLPTR)
        );
        pushButton_modifier_Emplacement->setText(QApplication::translate("MainWindow", "Mise \303\240 Jour", Q_NULLPTR));
        label_reservation->setText(QApplication::translate("MainWindow", "Reservation", Q_NULLPTR));
        pushButton_ajouter_Emplacement->setText(QApplication::translate("MainWindow", "Ajouter", Q_NULLPTR));
        pushButton_retour_emplacement->setText(QApplication::translate("MainWindow", "retour", Q_NULLPTR));
        label_photo_Emplacement->setText(QString());
        label_CIN->setText(QApplication::translate("MainWindow", "CIN ", Q_NULLPTR));
        pushButton_Supprimer->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        label_Nom->setText(QApplication::translate("MainWindow", "NOM", Q_NULLPTR));
        label_Num_Tel->setText(QApplication::translate("MainWindow", "Num de Tel", Q_NULLPTR));
        label_photo_Employe->setText(QString());
        label_Sexe->setText(QApplication::translate("MainWindow", "Sexe", Q_NULLPTR));
        pushButton_PDF->setText(QApplication::translate("MainWindow", "PDF", Q_NULLPTR));
        pushButton_MIseAJour->setText(QApplication::translate("MainWindow", "Mise \303\240 Jour", Q_NULLPTR));
        lineEdit_CIN->setText(QString());
        label_Date_naissance->setText(QApplication::translate("MainWindow", "Date de Naissance", Q_NULLPTR));
        comboBox_tri->clear();
        comboBox_tri->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "          Trier", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Tri par CIN Monatnt", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Tri par CIN Desendant", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Tri par Nom", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Tri par Date", Q_NULLPTR)
        );
        label_Prenom->setText(QApplication::translate("MainWindow", "PRENOM", Q_NULLPTR));
        pushButton_Afficher->setText(QApplication::translate("MainWindow", "Afficher", Q_NULLPTR));
        comboBox_Sexe->clear();
        comboBox_Sexe->insertItems(0, QStringList()
         << QString()
         << QApplication::translate("MainWindow", "Femme", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Homme", Q_NULLPTR)
        );
        label_Recherche_Employe->setText(QApplication::translate("MainWindow", "Recherche :", Q_NULLPTR));
        label_Email->setText(QApplication::translate("MainWindow", "Email", Q_NULLPTR));
        label_Adress->setText(QApplication::translate("MainWindow", "Adress", Q_NULLPTR));
        pushButton_Ajouter->setText(QApplication::translate("MainWindow", "Ajouter", Q_NULLPTR));
        pushButton_Reset->setText(QApplication::translate("MainWindow", "Reset", Q_NULLPTR));
        pushButton_retour_employer->setText(QApplication::translate("MainWindow", "retour", Q_NULLPTR));
        pushButton_miseajouravion->setText(QApplication::translate("MainWindow", "Mise \303\240 Jour", Q_NULLPTR));
        pushButton_PDFavion->setText(QApplication::translate("MainWindow", "PDF", Q_NULLPTR));
        pushButton_ajouteravion->setText(QApplication::translate("MainWindow", "Ajouter", Q_NULLPTR));
        pushButton_imprimeravion->setText(QApplication::translate("MainWindow", "Imprimer", Q_NULLPTR));
        label_arrivee->setText(QApplication::translate("MainWindow", "arrivee", Q_NULLPTR));
        label_nbplace->setText(QApplication::translate("MainWindow", "nbplace", Q_NULLPTR));
        label_duree->setText(QApplication::translate("MainWindow", "dure\303\251 vol", Q_NULLPTR));
        pushButton_afficheravion->setText(QApplication::translate("MainWindow", "Afficher", Q_NULLPTR));
        label_code->setText(QApplication::translate("MainWindow", "code", Q_NULLPTR));
        label_Recherche_avion->setText(QApplication::translate("MainWindow", "Recherche :", Q_NULLPTR));
        pushButton_supprimeravion->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        label_photo_avion->setText(QString());
        pushButton_statestiqueavion->setText(QApplication::translate("MainWindow", "Statestique", Q_NULLPTR));
        label_prix->setText(QApplication::translate("MainWindow", "prix", Q_NULLPTR));
        label_depart->setText(QApplication::translate("MainWindow", "depart", Q_NULLPTR));
        comboBox_trier_avion->clear();
        comboBox_trier_avion->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "   Trier", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Tri par Code", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Tri par nbplace", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Tri par Prix", Q_NULLPTR)
        );
        lineEdit_codeavion->setText(QString());
        pushButton_retour_avion->setText(QApplication::translate("MainWindow", "retour", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
